language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
install: sudo pip install . nose sphinx sphinx_rtd_theme
script: sudo nosetests && sudo sphinx-build -b html docs docs/_build
notifications:
    webhooks:
        - http://moriarty.thesharp.org:5000/travis/2c27baee8754c01522cf751c1ed393b1/
sudo: true
